name: Charge log (10 min)

on:
  schedule:
    - cron: "*/10 * * * *"   # Toutes les 10 minutes
  workflow_dispatch: {}       # Lancement manuel possible

permissions:
  contents: write

jobs:
  log:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Paris

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install tzdata (fuseaux horaires)
        run: |
          sudo apt-get update
          sudo apt-get install -y tzdata

      - name: Install Playwright
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          python -m playwright install --with-deps chromium

      - name: Run logger once
        run: |
          python logger_once.py

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "Append charge log $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          else
            echo "No changes to commit."
          fi
